version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: expense-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: melss
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: melss
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - expense-network

  backend:
    build: ./backend
    container_name: expense-tracker-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expense_tracker
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: melss
    ports:
      - "8080:8080"
    networks:
      - expense-network

  frontend:
    build: ./frontend
    container_name: expense-tracker-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - expense-network

networks:
  expense-network:

volumes:
  mysql-data: